package model;

public enum ActionNotice {
	HAND_SELECTED, CENTER_SELECTED, CONSTRUCT_SELECTED, COMMON_SELECTED, DISCARD_SELECTED, PLAYED_SELECTED,
	CENTER_DEFEATED,
	MECHANA_CONSTRUCT_PLAYED, HERO_PLAYED,
	HERO_ACQUIRED, CONSTRUCT_ACQUIRED,
	TURN_START, TURN_END,
	OPTION_SELECTED, REFUSED,
	NONE
}
