package model;

public enum GameAction {
	SELECT_HAND, SELECT_CENTER, SELECT_CONSTRUCT, SELECT_COMMON, SELECT_DISCARD,
	DEFEAT_CENTER, DEFEAT_ANY,
	PLAY_MECHANA_CONSTRUCT,
	ACQUIRE_HERO,
	TURN_START, TURN_END,
	SELECT_OPTION,
	NONE
}
