package model;

public enum GameAction {
	SELECT_HAND, SELECT_CENTER, SELECT_CONSTRUCT, SELECT_COMMON, SELECT_DISCARD, SELECT_PLAYED,
	DEFEAT_CENTER, DEFEAT_ANY,
	PLAY_MECHANA_CONSTRUCT, PLAY_HERO,
	ACQUIRE_HERO, ACQUIRE_CONSTRUCT,
	TURN_START, TURN_END,
	SELECT_OPTION, REFUSE,
	NONE
}
